/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazp1;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import cjb.ci.Validaciones;
import java.awt.event.KeyEvent;
import p1.Ejecucion;
import p1.Proceso;

/**
 *
 * @author Francisco
 */
public class NvoProceso extends javax.swing.JFrame
{

    /**
     * Creates new form NvoProceso
     */
    public NvoProceso()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        nombreP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroQ = new javax.swing.JTextField();
        numeroP = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancelarB = new javax.swing.JButton();
        okB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreP.setBackground(new java.awt.Color(255, 255, 224));
        nombreP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                nombrePActionPerformed(evt);
            }
        });
        nombreP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                nombrePKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                nombrePKeyTyped(evt);
            }
        });
        jPanel1.add(nombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 350, -1));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, 20));

        jLabel2.setText("Numero de Prioridad");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 120, 20));

        numeroQ.setBackground(new java.awt.Color(255, 255, 224));
        numeroQ.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                numeroQActionPerformed(evt);
            }
        });
        numeroQ.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                numeroQKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                numeroQKeyTyped(evt);
            }
        });
        jPanel1.add(numeroQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 350, -1));

        numeroP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        numeroP.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                numeroPKeyPressed(evt);
            }
        });
        jPanel1.add(numeroP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel3.setText("Numero de Quantums");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 130, 20));

        jLabel4.setFont(new java.awt.Font("Yu Mincho", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Nuevo Proceso");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 400, 60));

        cancelarB.setText("Cancelar");
        cancelarB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cancelarBActionPerformed(evt);
            }
        });
        cancelarB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                cancelarBKeyPressed(evt);
            }
        });
        jPanel1.add(cancelarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        okB.setText("Ok");
        okB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                okBActionPerformed(evt);
            }
        });
        okB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                okBKeyPressed(evt);
            }
        });
        jPanel1.add(okB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombrePActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nombrePActionPerformed
    {//GEN-HEADEREND:event_nombrePActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePActionPerformed

    private void numeroQActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_numeroQActionPerformed
    {//GEN-HEADEREND:event_numeroQActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroQActionPerformed

    private void okBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okBActionPerformed
    {//GEN-HEADEREND:event_okBActionPerformed
        // TODO add your handling code here:
        if (!nombreP.getText().equals("") && !numeroQ.getText().equals("") && numeroP.getSelectedIndex() != 0)
        {
            if (Principal.x == null)
            {
                Principal.x = new Ejecucion();
            }
            Principal.x.subirProc(new Proceso(numeroP.getSelectedIndex(), nombreP.getText(), Integer.parseInt(numeroQ.getText())),this);
            dispose();
        }else
        {
            Mensajes.error(this, "Los campos estan incompletos");
        }
    }//GEN-LAST:event_okBActionPerformed

    private void numeroQKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numeroQKeyTyped
    {//GEN-HEADEREND:event_numeroQKeyTyped
        // TODO add your handling code here:
        Validaciones.validaEntero(evt, 5, numeroQ.getText());

    }//GEN-LAST:event_numeroQKeyTyped

    private void numeroQKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numeroQKeyPressed
    {//GEN-HEADEREND:event_numeroQKeyPressed
        // TODO add your handling code here:
        Validaciones.enterEntero(this, evt, numeroQ, numeroP);
        Validaciones.validaCopyPaste(evt, this, numeroQ);
    }//GEN-LAST:event_numeroQKeyPressed

    private void nombrePKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombrePKeyPressed
    {//GEN-HEADEREND:event_nombrePKeyPressed
        // TODO add your handling code here:
        Validaciones.enterCNV(this, evt, nombreP, numeroQ);
        Validaciones.validaCopyPaste(evt, this, nombreP);
    }//GEN-LAST:event_nombrePKeyPressed

    private void nombrePKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_nombrePKeyTyped
    {//GEN-HEADEREND:event_nombrePKeyTyped
        // TODO add your handling code here:
        Validaciones.validaAlfanumerico(evt, 20, nombreP.getText());
    }//GEN-LAST:event_nombrePKeyTyped

    private void numeroPKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_numeroPKeyPressed
    {//GEN-HEADEREND:event_numeroPKeyPressed
        // TODO add your handling code here:
        if ('\n' == evt.getKeyChar() && numeroP.getSelectedIndex() != 0)
        {
            CtrlInterfaz.cambia(okB);
        }else
        {
            if ('\n' == evt.getKeyChar())
            {
                Mensajes.error(this, "Seleccione un nivel de Prioridad");
            }
        }
    }//GEN-LAST:event_numeroPKeyPressed

    private void okBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_okBKeyPressed
    {//GEN-HEADEREND:event_okBKeyPressed
        // TODO add your handling code here:
        if ('\n' == evt.getKeyChar())
        {
            okBActionPerformed(null);
        }
        if (evt.getKeyCode()==KeyEvent.VK_RIGHT || evt.getKeyCode()== KeyEvent.VK_LEFT)
        {
            CtrlInterfaz.cambia(cancelarB);
        }
    }//GEN-LAST:event_okBKeyPressed

    private void cancelarBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelarBActionPerformed
    {//GEN-HEADEREND:event_cancelarBActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelarBActionPerformed

    private void cancelarBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_cancelarBKeyPressed
    {//GEN-HEADEREND:event_cancelarBKeyPressed
        // TODO add your handling code here:
        if ('\n' == evt.getKeyChar())
        {
            cancelarBActionPerformed(null);
        }
        if (evt.getKeyCode()==KeyEvent.VK_LEFT|| evt.getKeyCode() == KeyEvent.VK_RIGHT)
        {
            CtrlInterfaz.cambia(okB);
        }
    }//GEN-LAST:event_cancelarBKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(NvoProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(NvoProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(NvoProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(NvoProceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new NvoProceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreP;
    private javax.swing.JComboBox<String> numeroP;
    private javax.swing.JTextField numeroQ;
    private javax.swing.JButton okB;
    // End of variables declaration//GEN-END:variables
}
