/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazp1;

import cjb.ci.CtrlInterfaz;
import cjb.ci.Mensajes;
import java.awt.event.KeyEvent;
import p1.Ejecucion;
import poo.ManArch;

/**
 *
 * @author Francisco
 */
public class Principal extends javax.swing.JFrame
{

    public static Ejecucion x = new Ejecucion();

    /**
     * Creates new form Principal
     */
    public Principal()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        salirB = new javax.swing.JButton();
        altasB = new javax.swing.JButton();
        bajasB = new javax.swing.JButton();
        procesarB = new javax.swing.JButton();
        consultaPB = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        altas = new javax.swing.JMenuItem();
        bajas = new javax.swing.JMenuItem();
        procesar = new javax.swing.JMenuItem();
        consultaP = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salirB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        salirB.setText("Salir");
        salirB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                salirBActionPerformed(evt);
            }
        });
        salirB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                salirBKeyPressed(evt);
            }
        });
        jPanel1.add(salirB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 260, 50));

        altasB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        altasB.setText("Altas");
        altasB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                altasBActionPerformed(evt);
            }
        });
        altasB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                altasBKeyPressed(evt);
            }
        });
        jPanel1.add(altasB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 260, 50));

        bajasB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bajasB.setText("Bajas");
        bajasB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bajasBActionPerformed(evt);
            }
        });
        bajasB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                bajasBKeyPressed(evt);
            }
        });
        jPanel1.add(bajasB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 260, 50));

        procesarB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        procesarB.setText("Procesar");
        procesarB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                procesarBActionPerformed(evt);
            }
        });
        procesarB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                procesarBKeyPressed(evt);
            }
        });
        jPanel1.add(procesarB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 260, 50));

        consultaPB.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        consultaPB.setText("Consulta de Procesos");
        consultaPB.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consultaPBActionPerformed(evt);
            }
        });
        consultaPB.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                consultaPBKeyPressed(evt);
            }
        });
        jPanel1.add(consultaPB, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 260, 50));

        jMenuBar2.setBackground(new java.awt.Color(0, 102, 204));

        jMenu3.setText("Menu");

        altas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        altas.setText("Altas de Procesos");
        altas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                altasActionPerformed(evt);
            }
        });
        jMenu3.add(altas);

        bajas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        bajas.setText("Bajas de Procesos");
        bajas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bajasActionPerformed(evt);
            }
        });
        jMenu3.add(bajas);

        procesar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        procesar.setText("Procesar");
        procesar.setToolTipText("");
        procesar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                procesarActionPerformed(evt);
            }
        });
        jMenu3.add(procesar);

        consultaP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        consultaP.setText("Consulta de Procesos");
        consultaP.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                consultaPActionPerformed(evt);
            }
        });
        jMenu3.add(consultaP);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1215, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        x = ((Ejecucion) ManArch.carga(this, "Procesos.dat"));
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void altasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_altasActionPerformed
    {//GEN-HEADEREND:event_altasActionPerformed
        // TODO add your handling code here:
        NvoProceso a = new NvoProceso();
        a.setVisible(true);
    }//GEN-LAST:event_altasActionPerformed

    private void bajasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bajasActionPerformed
    {//GEN-HEADEREND:event_bajasActionPerformed
        // TODO add your handling code here:
        if (x != null && x.getX().getR() != null)
        {
            QuitaProceso a = new QuitaProceso();
            a.setVisible(true);
        } else
        {
            Mensajes.error(this, "Error No hay datos");
        }
    }//GEN-LAST:event_bajasActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_procesarActionPerformed
    {//GEN-HEADEREND:event_procesarActionPerformed
        // TODO add your handling code here:
        if (x != null && x.getX().getR() != null)
        {
            Procesar a = new Procesar();
            a.setVisible(true);
        } else
        {
            Mensajes.error(this, "Error No hay datos");
        }
    }//GEN-LAST:event_procesarActionPerformed

    private void consultaPActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consultaPActionPerformed
    {//GEN-HEADEREND:event_consultaPActionPerformed
        // TODO add your handling code here:
        if (x != null && x.getX().getR() != null)
        {
            ConsultaProcesos a = new ConsultaProcesos();
            a.setVisible(true);
        } else
        {
            Mensajes.error(this, "Error No hay datos");
        }
    }//GEN-LAST:event_consultaPActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
        // TODO add your handling code here:
        ManArch.guarda(this, x, "Procesos.dat");
    }//GEN-LAST:event_formWindowClosing

    private void procesarBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_procesarBActionPerformed
    {//GEN-HEADEREND:event_procesarBActionPerformed
        // TODO add your handling code here:
        procesarActionPerformed(null);
    }//GEN-LAST:event_procesarBActionPerformed

    private void altasBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_altasBActionPerformed
    {//GEN-HEADEREND:event_altasBActionPerformed
        // TODO add your handling code here:
        altasActionPerformed(null);
    }//GEN-LAST:event_altasBActionPerformed

    private void bajasBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bajasBActionPerformed
    {//GEN-HEADEREND:event_bajasBActionPerformed
        // TODO add your handling code here:
        bajasActionPerformed(null);
    }//GEN-LAST:event_bajasBActionPerformed

    private void consultaPBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_consultaPBActionPerformed
    {//GEN-HEADEREND:event_consultaPBActionPerformed
        // TODO add your handling code here:
        consultaPActionPerformed(null);
    }//GEN-LAST:event_consultaPBActionPerformed

    private void salirBActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_salirBActionPerformed
    {//GEN-HEADEREND:event_salirBActionPerformed
        // TODO add your handling code here:
        ManArch.guarda(this, x, "Procesos.dat");
        dispose();
    }//GEN-LAST:event_salirBActionPerformed

    private void altasBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_altasBKeyPressed
    {//GEN-HEADEREND:event_altasBKeyPressed
        // TODO add your handling code here:
        if ('\n' == evt.getKeyChar())
        {
            altasBActionPerformed(null);
        }
        if (KeyEvent.VK_UP == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(salirB);
        }
        if (KeyEvent.VK_DOWN == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(bajasB);
        }
    }//GEN-LAST:event_altasBKeyPressed

    private void bajasBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_bajasBKeyPressed
    {//GEN-HEADEREND:event_bajasBKeyPressed
        // TODO add your handling code here:
        if ('\n' == evt.getKeyChar())
        {
            bajasBActionPerformed(null);
        }
        if (KeyEvent.VK_UP == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(altasB);
        }
        if (KeyEvent.VK_DOWN == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(procesarB);
        }
    }//GEN-LAST:event_bajasBKeyPressed

    private void procesarBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_procesarBKeyPressed
    {//GEN-HEADEREND:event_procesarBKeyPressed
        // TODO add your handling code here:
        if ('\n' == evt.getKeyChar())
        {
            procesarBActionPerformed(null);
        }
        if (KeyEvent.VK_UP == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(bajasB);
        }
        if (KeyEvent.VK_DOWN == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(consultaPB);
        }
    }//GEN-LAST:event_procesarBKeyPressed

    private void consultaPBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_consultaPBKeyPressed
    {//GEN-HEADEREND:event_consultaPBKeyPressed
        // TODO add your handling code here:
        if ('\n' == evt.getKeyChar())
        {
            consultaPBActionPerformed(null);
        }
        if (KeyEvent.VK_UP == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(procesarB);
        }
        if (KeyEvent.VK_DOWN == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(salirB);
        }
    }//GEN-LAST:event_consultaPBKeyPressed

    private void salirBKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_salirBKeyPressed
    {//GEN-HEADEREND:event_salirBKeyPressed
        // TODO add your handling code here:
        if ('\n' == evt.getKeyChar())
        {
            salirBActionPerformed(null);
        }
        if (KeyEvent.VK_UP == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(consultaPB);
        }
        if (KeyEvent.VK_DOWN == evt.getKeyCode())
        {
            CtrlInterfaz.cambia(altasB);
        }
    }//GEN-LAST:event_salirBKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem altas;
    private javax.swing.JButton altasB;
    private javax.swing.JMenuItem bajas;
    private javax.swing.JButton bajasB;
    private javax.swing.JMenuItem consultaP;
    private javax.swing.JButton consultaPB;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem procesar;
    private javax.swing.JButton procesarB;
    private javax.swing.JButton salirB;
    // End of variables declaration//GEN-END:variables
}
